# Generated by Django 4.2.7 on 2025-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='description_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='store_produ_descrip_dfecae_idx'),
        ),
    ]
