# Generated by Django 4.2.7 on 2025-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (masalan: jL14SRWKA6c)', max_length=50),
        ),
    ]
