# Generated by Django 4.2.7 on 2025-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauth',
            name='session_token',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramauth',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='telegramauth',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
