# Generated by Django 4.2.7 on 2025-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_paymentsettings_admin_chat_id_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
