# Generated by Django 4.2.7 on 2025-07-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramauth',
            name='session_token',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
