# Generated by Django 4.2.7 on 2025-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_telegramauth_session_token_alter_telegramauth_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauth',
            name='chat_id',
            field=models.TextField(default='default_id'),
        ),
    ]
