# Generated by Django 4.2.7 on 2025-08-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='title_en',
            new_name='title_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='description_en',
            new_name='description_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name_en',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='description_en',
            new_name='description_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='name_en',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_en',
            new_name='description_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='description_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_description_en',
            new_name='meta_description_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_title_en',
            new_name='meta_title_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_en',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='short_description_en',
            new_name='short_description_uz_Cyrl',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (masalan: jL14SRWKA6c)', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
