# Generated by Django 4.2.7 on 2025-07-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userprofile',
        ),
    ]
