version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  bot:
    build: .
    command: python bot.py
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

networks:
  app_network:
    driver: bridge