from .home_views import *
from .ajax_views import *
from .admin_views import *
from .other_views import *
from .model_views import *
from .banner_views import *
from .brands_views import *
from .category_views import *
from .product_views import *
from .order_views import *
